menus:
	- 
		name: 首页
		link: /
	- 
		name: 分类
		link: categories/
	- 
		name: 开源项目
		link: open-source/
	- 
		name: 留言板
		link: message/

# Profile
profile:
	location: Guangzhou, China
	github: devinzhong
	#stackoverflow: 
		#title: yumemor
		#href: http://stackoverflow.com/users/5662132/yumemor
	#organization: 组织/公司

#Github
github: 
	username: devinzhong
  popular_repos: [vue-im,blog]

#Comments
#duoshuo_username: way2hacker # 多说配置
disqus_username: way2hacker # disqus 配置

# Search 
# google | local
search:
    use: local
